remove if/else and dependentSchema from extension in devPreview schema
OfficeDev/microsoft-teams-app-schema pull request #171
Opened 2023-05-11 22:52 UTC by charlesji-msft-teams

2023-05-12 19:29 UTC, sim4r4 approved these changes

2023-05-15 15:51 UTC, sim4r4 requested changes
Since the same schema is now used for menu and button, "actionId" should also be removed from the "required" section since that was only required for button before.

2023-05-15 18:40 UTC, sim4r4 approved these changes

2023-05-16 01:25 UTC, joseflms approved these changes
As far as I can tell, this change should be fine.  Approving.

2023-05-18 22:56 UTC, AkJo approved these changes

2023-05-18 22:56 UTC, merged